/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cropsimulation;
//hhha
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author AMMC
 */
public class GRAFICA_EXP extends javax.swing.JFrame {

    /**
     * Creates new form Grafica
     */
    public GRAFICA_EXP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        btnG = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtg4 = new javax.swing.JTextField();
        txtg6 = new javax.swing.JTextField();
        txtg5 = new javax.swing.JTextField();
        txtg3 = new javax.swing.JTextField();
        txtg2 = new javax.swing.JTextField();
        txtg1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ganancias mes 6");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 306, 147, 26));

        jLabel2.setText("Ganancias mes 3");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 138, 147, 26));

        jLabel3.setText("Ganancias mes 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 90, 147, 26));

        jLabel4.setText("Ganancias mes 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 42, 147, 29));

        jLabel5.setText("Ganancias mes 5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 255, 147, 26));

        jLabel6.setText("Ganancias mes 4");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 206, 147, 26));

        txt3.setText("jTextField1");
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 138, 112, 48));

        txt2.setText("jTextField1");
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 112, 30));

        txt1.setText("jTextField1");
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 41, 112, 31));

        txt4.setText("jTextField1");
        getContentPane().add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 204, 112, 31));

        txt6.setText("jTextField1");
        txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt6ActionPerformed(evt);
            }
        });
        getContentPane().add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 112, 30));

        txt5.setText("jTextField1");
        getContentPane().add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 253, 112, 31));

        btnG.setText("GRAFICAR");
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });
        getContentPane().add(btnG, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 516, 178, 61));

        jLabel7.setText("GANANCIA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 11, 99, 20));

        jLabel8.setText("MES");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 11, 99, 20));

        txtg4.setText("jTextField1");
        getContentPane().add(txtg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 204, 112, 31));

        txtg6.setText("jTextField1");
        getContentPane().add(txtg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 302, 112, 35));

        txtg5.setText("jTextField1");
        getContentPane().add(txtg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 253, 112, 31));

        txtg3.setText("jTextField1");
        getContentPane().add(txtg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 138, 112, 48));

        txtg2.setText("jTextField1");
        getContentPane().add(txtg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 87, 112, 33));

        txtg1.setText("jTextField1");
        getContentPane().add(txtg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 41, 112, 31));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        // GRÁFICA
        int pos = 0;
        double pron;
        double A=0.99;
        double [] t = new double[6];
        double G1 = Double.parseDouble(txtg1.getText());
        double G2 = Double.parseDouble(txtg2.getText());
        double G3 = Double.parseDouble(txtg3.getText());
        double G4 = Double.parseDouble(txtg4.getText());
        double G5 = Double.parseDouble(txtg5.getText());
        double G6 = Double.parseDouble(txtg6.getText());
        //double [] x= {1, 2, 3, 4, 5, 6};
        double [] y= {G1, G2, G3, G4, G5, G6};
        
        String M1=txt1.getText();
        String M2=txt2.getText();
        String M3=txt3.getText();
        String M4=txt4.getText();
        String M5=txt5.getText();
        String M6=txt6.getText();
        
        String titulo="GANANCIAS";
        for(int i=0; i<t.length; i++){
            if(i==0){
                t[0]=G1;
                y[0]=G1;
            }
            if(i>0&&i<6){    
                t[i]=t[i-1]+(A*(y[i-1]-t[i-1])); 
            }
            if(i==6){
                t[i]=t[i-1]+(A*(y[i-1]-t[i-1]));
            }
        }  
        pron=t[5]+(A*(y[5]-t[5]));
        double GG1=t[0];
        double GG2=t[1];
        double GG3=t[2];
        double GG4=t[3];
        double GG5=t[4];
        double GG6=t[5];
        double GG7=pron;
        
        
        try{
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ds.addValue(G1, M1, "");
            ds.addValue(G2, M2, "");
            ds.addValue(G3, M3, "");
            ds.addValue(G4, M4, "");
            ds.addValue(G5, M5, "");
            ds.addValue(G6, M6, "");
            ds.addValue(GG7, "Pronóstico", "");
            
            JFreeChart jf=ChartFactory.createBarChart3D(titulo, "MES", "", ds, PlotOrientation.HORIZONTAL, true, true, true);
            ChartFrame f=new ChartFrame("SIMULACIÓN",jf);
            f.setSize(1000,600);
            f.setLocationRelativeTo(null);
            f.setVisible(true);
        }catch (Exception e){
            System.out.println("ERROR "+e);
            
        }
        
    }//GEN-LAST:event_btnGActionPerformed

    private void txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GRAFICA_EXP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GRAFICA_EXP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GRAFICA_EXP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GRAFICA_EXP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GRAFICA_EXP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txtg1;
    private javax.swing.JTextField txtg2;
    private javax.swing.JTextField txtg3;
    private javax.swing.JTextField txtg4;
    private javax.swing.JTextField txtg5;
    private javax.swing.JTextField txtg6;
    // End of variables declaration//GEN-END:variables
}
