/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cropsimulation;

import java.util.Date;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author AMMC
 */
public class GRAFICA_EXP1 extends javax.swing.JFrame {

    /**
     * Creates new form Grafica
     */
    public GRAFICA_EXP1() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        jlMes.setVisible(false);
        txtMes7.setVisible(false);
        jlMes7.setVisible(false);
        txtMes8.setVisible(false);
        jlMes8.setVisible(false);
        txtMes9.setVisible(false);
        jlMes9.setVisible(false);
        txtMes10.setVisible(false);
        jlMes10.setVisible(false);
        txtMes11.setVisible(false);
        jlMes11.setVisible(false);
        txtMes12.setVisible(false);
        jlMes12.setVisible(false);
    }
   
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnG = new javax.swing.JButton();
        jlMes = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtg4 = new javax.swing.JTextField();
        txtg6 = new javax.swing.JTextField();
        txtg5 = new javax.swing.JTextField();
        txtg3 = new javax.swing.JTextField();
        txtg2 = new javax.swing.JTextField();
        txtg1 = new javax.swing.JTextField();
        listaMes = new javax.swing.JComboBox<>();
        jlMes12 = new javax.swing.JLabel();
        jlMes9 = new javax.swing.JLabel();
        jlMes8 = new javax.swing.JLabel();
        jlMes7 = new javax.swing.JLabel();
        jlMes11 = new javax.swing.JLabel();
        jlMes10 = new javax.swing.JLabel();
        txtMes10 = new javax.swing.JTextField();
        txtMes12 = new javax.swing.JTextField();
        txtMes11 = new javax.swing.JTextField();
        txtMes9 = new javax.swing.JTextField();
        txtMes8 = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtMes7 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Mes 6");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 40, 26));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Mes 3");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 40, 26));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Mes 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 40, 26));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Año");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 40, 29));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Mes 5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 40, 26));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Mes 4");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 40, 26));

        btnG.setText("GRAFICAR");
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });
        getContentPane().add(btnG, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 178, 61));

        jlMes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlMes.setText("GANANCIA");
        getContentPane().add(jlMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 99, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("MES");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 99, 20));

        txtg4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 112, 30));

        txtg6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 112, 30));

        txtg5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 112, 30));

        txtg3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 112, 30));

        txtg2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 112, 30));

        txtg1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 112, 30));

        listaMes.setMaximumRowCount(12);
        listaMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        listaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaMesActionPerformed(evt);
            }
        });
        getContentPane().add(listaMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 112, 30));

        jlMes12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlMes12.setText("Mes 12");
        getContentPane().add(jlMes12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 50, 26));

        jlMes9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlMes9.setText("Mes 9");
        getContentPane().add(jlMes9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 50, 26));

        jlMes8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlMes8.setText("Mes 8");
        getContentPane().add(jlMes8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 50, 26));

        jlMes7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlMes7.setText("Mes 7");
        getContentPane().add(jlMes7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 50, 29));

        jlMes11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlMes11.setText("Mes 11");
        getContentPane().add(jlMes11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 50, 26));

        jlMes10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlMes10.setText("Mes 10");
        getContentPane().add(jlMes10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 50, 26));

        txtMes10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtMes10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 112, 30));

        txtMes12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtMes12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 112, 30));

        txtMes11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtMes11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 112, 30));

        txtMes9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtMes9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 112, 30));

        txtMes8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtMes8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 112, 30));

        txtAnio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 112, 30));

        jLabel15.setBackground(new java.awt.Color(56, 99, 7));
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 70));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("GANANCIA");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 99, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Calcular interpolación");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 180, 60));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Mes 1");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 40, 29));

        txtMes7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtMes7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 112, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("6 meses");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("12 meses");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        jLabel18.setText("Seleccione el numero de intervalos:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        // GRÁFICA
        //Vector de meses
        int posicion=0;
        String vMeses[]={"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};  
        String mesSeleccionado = (String) listaMes.getSelectedItem(); //Se obtiene el mes que el usuario selecciono
        var fecha = new Date();
        var diaActual = fecha.getDate();
        var mesActual = fecha.getMonth();//viene con valores de 0 al 11
        String anioActual=txtAnio.getText();
        
        //Obtener la posicion del Item dentro del Vector
        for(int i=0; i<12; i++){
            if(vMeses[i].equalsIgnoreCase(mesSeleccionado)){
                posicion=i;
            }
        }
        String mesActual1=mesActual+"";
        String posicion1=posicion+"";
        
        /*Si la posicion es mayor a mesActual y anio es igual a 2021 no se podra ingresar los datos */
        if(mesActual1.equalsIgnoreCase(posicion1)){
            JOptionPane.showMessageDialog(null,"Datos invalidos, revisar los datos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
            
        
       /*if(mesSeleccionado.equalsIgnoreCase(vMeses[mesActual]+"")&&anioActual.equalsIgnoreCase("2021")){
            JOptionPane.showMessageDialog(null, "Datos incorrectos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else
        {
            
        }*/
        

        //  var M1=listaMes.getSelectedItem();
        
        /*if(mesActual){
            
        }*/
      

    /*    int pos = 0;
        double pron;
        double A=0.99;
        double [] t = new double[6];
        double G1 = Double.parseDouble(txtg1.getText());
        double G2 = Double.parseDouble(txtg2.getText());
        double G3 = Double.parseDouble(txtg3.getText());
        double G4 = Double.parseDouble(txtg4.getText());
        double G5 = Double.parseDouble(txtg5.getText());
        double G6 = Double.parseDouble(txtg6.getText());
        //double [] x= {1, 2, 3, 4, 5, 6};
        double [] y= {G1, G2, G3, G4, G5, G6};*/
        
        //String M1=txt1.getText();
       /* String M2=txt2.getText();
        String M3=txt3.getText();
        String M4=txt4.getText();
        String M5=txt5.getText();
        String M6=txt6.getText();
        
        String titulo="GANANCIAS";
        for(int i=0; i<t.length; i++){
            if(i==0){
                t[0]=G1;
                y[0]=G1;
            }
            if(i>0&&i<6){    
                t[i]=t[i-1]+(A*(y[i-1]-t[i-1])); 
            }
            if(i==6){
                t[i]=t[i-1]+(A*(y[i-1]-t[i-1]));
            }
        }  
        pron=t[5]+(A*(y[5]-t[5]));
        double GG1=t[0];
        double GG2=t[1];
        double GG3=t[2];
        double GG4=t[3];
        double GG5=t[4];
        double GG6=t[5];
        double GG7=pron;
        
        
        try{
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ds.addValue(G1, M1, "");
            ds.addValue(G2, M2, "");
            ds.addValue(G3, M3, "");
            ds.addValue(G4, M4, "");
            ds.addValue(G5, M5, "");
            ds.addValue(G6, M6, "");
            ds.addValue(GG7, "Pronóstico", "");
            
            JFreeChart jf=ChartFactory.createBarChart3D(titulo, "MES", "", ds, PlotOrientation.HORIZONTAL, true, true, true);
            ChartFrame f=new ChartFrame("SIMULACIÓN",jf);
            f.setSize(1000,600);
            f.setLocationRelativeTo(null);
            f.setVisible(true);
        }catch (Exception e){
            System.out.println("ERROR "+e);
            
        }*/
        
    }//GEN-LAST:event_btnGActionPerformed

    private void listaMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaMesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jlMes.setVisible(true);
        txtMes7.setVisible(true);
        jlMes7.setVisible(true);
        txtMes8.setVisible(true);
        jlMes8.setVisible(true);
        txtMes9.setVisible(true);
        jlMes9.setVisible(true);
        txtMes10.setVisible(true);
        jlMes10.setVisible(true);
        txtMes11.setVisible(true);
        jlMes11.setVisible(true);
        txtMes12.setVisible(true);
        jlMes12.setVisible(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jlMes.setVisible(false);
        txtMes7.setVisible(false);
        jlMes7.setVisible(false);
        txtMes8.setVisible(false);
        jlMes8.setVisible(false);
        txtMes9.setVisible(false);
        jlMes9.setVisible(false);
        txtMes10.setVisible(false);
        jlMes10.setVisible(false);
        txtMes11.setVisible(false);
        jlMes11.setVisible(false);
        txtMes12.setVisible(false);
        jlMes12.setVisible(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GRAFICA_EXP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GRAFICA_EXP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GRAFICA_EXP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GRAFICA_EXP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GRAFICA_EXP1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnG;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel jlMes;
    private javax.swing.JLabel jlMes10;
    private javax.swing.JLabel jlMes11;
    private javax.swing.JLabel jlMes12;
    private javax.swing.JLabel jlMes7;
    private javax.swing.JLabel jlMes8;
    private javax.swing.JLabel jlMes9;
    private javax.swing.JComboBox<String> listaMes;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtMes10;
    private javax.swing.JTextField txtMes11;
    private javax.swing.JTextField txtMes12;
    private javax.swing.JTextField txtMes7;
    private javax.swing.JTextField txtMes8;
    private javax.swing.JTextField txtMes9;
    private javax.swing.JTextField txtg1;
    private javax.swing.JTextField txtg2;
    private javax.swing.JTextField txtg3;
    private javax.swing.JTextField txtg4;
    private javax.swing.JTextField txtg5;
    private javax.swing.JTextField txtg6;
    // End of variables declaration//GEN-END:variables
}
