/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
Editado
 */

package com.mycompany.cropsimulation;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;

/**
 *
 * @author sofia
 */
public class MENU_GLOSARIO extends javax.swing.JFrame {

    /**
     * Creates new form REGISTRAR_DATOS
     */
    public MENU_GLOSARIO() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_capital = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_cultivo = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menú");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 20, 340, 30);

        jLabel1.setBackground(new java.awt.Color(56, 99, 7));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1400, 70);

        jLabel3.setBackground(new java.awt.Color(208, 244, 198));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("D0F4C6");
        jLabel3.setToolTipText("");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1120, 100, 80, 40);

        jLabel4.setBackground(new java.awt.Color(143, 161, 17));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("8FA111");
        jLabel4.setToolTipText("");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(760, 100, 80, 40);

        jLabel5.setBackground(new java.awt.Color(56, 99, 9));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("386309");
        jLabel5.setToolTipText("");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(850, 100, 80, 40);

        jLabel6.setBackground(new java.awt.Color(213, 194, 30));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("D5C21E");
        jLabel6.setToolTipText("");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(940, 100, 80, 40);

        jLabel7.setBackground(new java.awt.Color(191, 219, 106));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BFDB6A");
        jLabel7.setToolTipText("");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1030, 100, 80, 40);

        btn_capital.setBackground(new java.awt.Color(143, 161, 17));
        btn_capital.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_capital.setForeground(new java.awt.Color(255, 255, 255));
        btn_capital.setText("Capital");
        btn_capital.setBorder(null);
        btn_capital.setFocusPainted(false);
        btn_capital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capitalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_capital);
        btn_capital.setBounds(70, 120, 200, 100);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Producción planeada de cultivos con propósitos no bioenergéticos");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 610, 540, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Rendimiento actual (t/ha)");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(350, 180, 250, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Número de cosechas por año");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(350, 310, 250, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Área de producción total (ha)");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(350, 370, 250, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Abastecimiento de agua");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(350, 430, 250, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Rendimiento potencial (t/ha)");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });
        getContentPane().add(jLabel19);
        jLabel19.setBounds(350, 490, 240, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Producción intensificada");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });
        getContentPane().add(jLabel18);
        jLabel18.setBounds(350, 550, 240, 30);

        labelDescripcion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(labelDescripcion);
        labelDescripcion.setBounds(690, 180, 590, 280);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Producción anual (t/año)");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        getContentPane().add(jLabel14);
        jLabel14.setBounds(350, 250, 250, 30);

        btn_cultivo.setBackground(new java.awt.Color(143, 161, 17));
        btn_cultivo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_cultivo.setForeground(new java.awt.Color(255, 255, 255));
        btn_cultivo.setText("Cultivo");
        btn_cultivo.setBorder(null);
        btn_cultivo.setFocusPainted(false);
        btn_cultivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cultivoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cultivo);
        btn_cultivo.setBounds(70, 290, 200, 100);

        jLabel17.setBackground(new java.awt.Color(191, 219, 106));
        jLabel17.setOpaque(true);
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 70, 340, 740);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Glosario");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(350, 100, 220, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-6, 70, 1470, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_capitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capitalActionPerformed
        // TODO add your handling code here:
        GRAFICA_EXP a = new GRAFICA_EXP();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_capitalActionPerformed

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
       labelDescripcion.setText("<html>El rendimiento del cultivo seleccionado obtenido en el área de análisis, según las prácticas de producción agrícola existente (nivel de entrada), expresado en " +
                                "toneladas por hectárea</html>");
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
        labelDescripcion.setText("<html>El número de cosechas de los cultivos analizados " +
                                "en un año calendario.</html>");                        
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
       labelDescripcion.setText("<html>La superficie del terreno utilizado para la producción " +
                                "del cultivo analizado, expresada en hectáreas.</html>");
                           
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
        labelDescripcion.setText("<html>La fuente y sistema de suministro de agua que se utiliza " +
                                "para la producción agrícola.</html>");
       
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        labelDescripcion.setText("<html>El rendimiento del cultivo analizado que puede obtenerse " +
                                "potencialmente, en función del nivel de entrada seleccionado " +
                                "y la aptitud de la tierra del área analizada.</html>");
                                
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        labelDescripcion.setText("<html>La producción del cultivo seleccionado que puede lograrse con el " +
                                "rendimiento potencial (previsto), es decir, producción prevista.</html>");
                                
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
       labelDescripcion.setText("<html>La producción del cultivo seleccionado para " +
                                "un propósito diferente al de la producción de "+
                                "biocombustibles líquidos. Refleja el consumo "+
                                "previsto de los cultivos analizados con destino "+
                                "a la alimentación, forraje, exportación, etc.</html>");
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
           labelDescripcion.setText("");
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
           labelDescripcion.setText("");
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
           labelDescripcion.setText("");
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
           labelDescripcion.setText("");
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
        // TODO add your handling code here:
           labelDescripcion.setText("");
    }//GEN-LAST:event_jLabel19MouseExited

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        // TODO add your handling code here:
           labelDescripcion.setText("");
    }//GEN-LAST:event_jLabel18MouseExited

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
           labelDescripcion.setText("");
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
        labelDescripcion.setText("<html>La cantidad del cultivo analizado producido en un año calendario en el área " +
"de análisis, según las prácticas de producción agrícola existente (nivel de entrada), expresada en " +
"toneladas.</html>");
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseExited

    private void btn_cultivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cultivoActionPerformed
        // TODO add your handling code here:
        GRAFICA_EXP a = new GRAFICA_EXP();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_cultivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTRAR_DATOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTRAR_DATOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTRAR_DATOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTRAR_DATOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTRAR_DATOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capital;
    private javax.swing.JButton btn_cultivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelDescripcion;
    // End of variables declaration//GEN-END:variables
}
